### ISSUE TITLE
Bundlewatch Github status not working?

### ISSUE THREAD

**Issue by mrlubos** [bundlewatch/bundlewatch#220]
**Do you want to request a *feature* or report a *bug*?**

Bug.

(Slack link above not working btw)

**What is the current behavior?**

Unable to get Github status check to work with Github actions.

**If the current behavior is a bug, please provide the steps to reproduce.**

Following the official [documentation](https://bundlewatch.io/#/README).

1. Install bundlewatch.
2. Create config file.
3. Add `BUNDLEWATCH_GITHUB_TOKEN` secret to the project.
4. Add build command and bundlewatch CLI command to my existing Github Actions workflow.
5. Commit these changes.
6. Observe everything works and results are saved.
7. Open a new pull request.
8. Observe everything works again and the results are diffed against the base branch.
9. Observe no status check appears on the pull request.

`package.json`

```sh
"size": "bundlewatch --config .bundlewatchrc.json"
```

`.bundlewatchrc.json`

```json
{
  "files": [
    {
      "maxSize": "20 KB",
      "path": "build/static/js/*.js"
    }
  ],
  "ci": {
    "trackBranches": ["main"]
  }
}
```

`.github/workflows/workflow.yml`

```yml
name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn size
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_BRANCH_BASE: main
```

**What is the expected behavior?**

A failing or succeeding pull request check appears on Github.

**If this is a feature request, what is motivation or use case for changing the behavior?**

-

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

Node 12.18.3
bundlewatch 0.2.7

**Comment by olegshilov** [comment]
Have the same issue

**Comment by sjwilczynski** [comment]
Same issue for me

**Comment by iamogbz** [comment]
@mrlubos mind providing some logs from when the bundlewatch script is run i.e. `yarn size`. Might be an issue with the first check not having something to diff against master.

**Comment by sjwilczynski** [comment]
@iamogbz I have the same issue. You can see the logs for bundlewatch action running [here](https://github.com/sjwilczynski/Activity-tracker/runs/1382448239?check_suite_focus=true). The bundlewatch configuration is in the root [package.json](https://github.com/sjwilczynski/Activity-tracker/blob/b614161efd3196eaa570125f567c7aaf52d49ec0/package.json) file.

**Comment by indocomsoft** [comment]
Same thing is happening to https://github.com/pinda-fun/pinda-fun

**Comment by izi-p** [comment]
Hello I am currently having the same issue, how did you manage to make it work @indocomsoft  @mrlubos @sjwilczynski 🙏

**Comment by sjwilczynski** [comment]
@izi-p i didn't manage to fix it unfortunately

**Comment by izi-p** [comment]
Somehow it does not work with github actions and the commit that is sent to result page is a weird merge commit instead of the head commit of the pull request.

I managed to fix this by passing manually the commit sha pointing to the head commit of the pull request in my github action


checksize.yml
```
      - name: Run bundlewatch
        run: yarn bundlewatch --config bundlewatch.config.json
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
```

cc @sjwilczynski
