### ISSUE TITLE
Fundamental instructions missing from documentation

### ISSUE THREAD

**Issue by fregante** [bundlewatch/bundlewatch#242]
On both the readme and the site, these are the instructions:

> # Getting Started
> 
> Install the BundleWatch package:
> 
> - NPM: `npm install bundlewatch --save-dev`
> - Yarn: `yarn add bundlewatch --dev`
> 
> Add some basic configuration to your `package.json`
> 
> ```json
> {
>     "name": "my package name",
>     "version": "0.0.1",
>     "bundlewatch": {
>         "files": [
>             {
>                 "path": "myfolder/*.js",
>                 "maxSize": "100kB"
>             }
>         ]
>     }
> }
> ```
> 
> Usage:
> 
> - NPM: `npm run bundlewatch`
> - Yarn: `yarn run bundlewatch`
> 
> This will give you command line output. If you want BundleWatch to report build status on your pull requests, see below.

Now run the last command:

```sh
❯ npm run bundlewatch
npm ERR! missing script: bundlewatch
```

**Comment by fregante** [comment]
Also on the ["Using bundlewatch"](https://bundlewatch.io/#/getting-started/using-bundlewatch) page nowhere does it say how and where to make the GitHub App work.

I assume that this piece information is missing:

<em>

In your CI that runs in every PR, run `npm run bundlewatch` after your build. For example on GitHub Actions:

```yml
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: 8fc08494d51041a393beb
```

</em>
