### ISSUE TITLE
Branches with slash (`/`) in their name are not supporten in GitHub Actions

### ISSUE THREAD

**Issue by tomalec** [bundlewatch/bundlewatch#422]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When I run bundlewatch in a GitHub action on a branch that contains a `/` it fails to recognize it and cuts it after the first slash (`fix/issue/123-slashes-in-branch`).

```
[INFO] master !== fix, no results saved
[INFO] fix is not a branch to track, no results saved
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Setup GH Action
	```yml
    - name: Run bundlewatch
      run: npx bundlewatch
      env:
        BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
	```
2. Push a change to a branch with a slash, like `fix/issue/123-slashes-in-branch`

**What is the expected behavior?**

All branch names are supported.

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

I'm using latest bundlewatch `0.3.2`.

I bet, the reason for this bug, is the bug in `ci-env` https://github.com/siddharthkp/ci-env/blob/master/index.js#L122 reading only the part between the second and third slash.

Fix seems to be waiting at https://github.com/siddharthkp/ci-env/pull/43
